name: ecommerce_urban
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.2.1
  get: ^4.7.2
  fl_chart: ^1.1.1
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  line_icons: ^2.0.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.4.0
  
#  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
